# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Scraper - Update Data

on:
  schedule:
    - cron: '30 10 * * *' # 주기적으로 실행하기 위한 스케줄링 - cron 설정 (매일 오전 10시 30분)
  push:
    branchs: [master]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Scraper with python
      run: |
        python "scraper.py"
    - name: Commits
      run: |
        git config --local user.email "greensohee88@naver.com"
        git config --local user.name "soheekim"
        git add news.json
        git commit -m "auto - update data with scraping"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $
